### ISSUE TITLE
Browser Auto-Complete doesn't work in Conveyor plugin

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#104]
There is something odd going on in the conveyor plugin. I am more likely to encounter this than others since I tend to re-create the same flows over and over again testing things.

but if I use the auto-complete that my browser offers then often the text that I didn't physically type, but that the auto complete filled in doesn't get captures. My guess is we're watching for a keypress or lift event that doesn't ever happen in the case of auto complete?

**Comment by malave** [comment]
@wrathagom The autocomplete attribute was not set properly and it now works on all text field, except on one scenario on Safari when using the value `"name"` in the `id` and `autocomplete` attributes of an `input` field or even on its label, it will show the user contacts.
