### ISSUE TITLE
The way index patterns are stored changes in 6.0

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#110]
Because of the removal of type how index patterns are being stored is going to change.

We can handle this two ways: install a global flow that matches the ES version Or build code into he global flow to handle version differences.

Long term it will likely only be feasible to have a global flow per version as we wont want the global flow to become too colossal. But for now this single instance it may make more sense to just put it in the same flow.

**Comment by spg-matt** [comment]
This is a bigger change than Caleb or I expected. Not only is the way index-patterns stored very different, but to create them properly you have to use the new stored objects API.

Those two things together are okay to deal with, but the way you link to an index pattern in the discover page is very different. This will require a change to the plugin to handle. Even worse than that it will likely require a change that implements knowledge of which version of Kibana it is running against.

**Comment by spg-matt** [comment]
Found a fix
