### ISSUE TITLE
Allow Sources to Indicate Pre-Built Dashboards, Alerts, Etc

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#120]
Some sources are going to start coming with pre-build dashboards, alerts, maybe even machine learning jobs. When we define the source we'll do something like:

```
{
  "name": Github Repo Statistics,
  "description": "Use this source to follow a GitHub repository and collect statistics from it",
  "hasDashboards": true,
  "hasAlerts": true,
  "hasLearning": false,
  "flow": { .... }
}
```

Ideally the fields wouldn't be required that way we don't break compatibility with existing source definitions.

@broham89 can you design this one out? See the image below. We'll need the HTML/CSS to adapt the source "cards" and then an icon for when the source has dashboards, alerts, and learning.

<img width="1904" alt="2018-02-22_10-50-14" src="https://user-images.githubusercontent.com/1779894/36548712-ff0f921c-17be-11e8-8202-2912dfadef7a.png">

**Comment by broham89** [comment]
@wrathagom is this the look that you're going for? "Dashboards, Alerts, and MLearning" icons top-right of the source cards to help users quickly tell if that card has those listed?
<img width="603" alt="screen shot 2018-02-22 at 5 03 09 pm" src="https://user-images.githubusercontent.com/11262149/36569175-58b8a406-17f2-11e8-9e9b-9d18c32854c5.png">

**Comment by wrathagom** [comment]
Yep looks good. Maybe the Machine learning should be the bot with a graduation cap on? Can't really tell what it means as is. Ideally they would have tooltips that just said `This source contains pre-packaged dashboards` etc.

@malave does it help at all if he gives you HTML/CSS?

**Comment by broham89** [comment]
Added elements:
- **index.html** line **80 - 83** has `.indicators` holding the three icons.
- **css/scss/components/__card.scss_** line **19 - 27** contains the style and position of the icons.
- **js/script.js** line **25 -28** added a quicker tooltip reveal. 

[conveyor-ui.zip](https://github.com/samtecspg/conveyor/files/1753199/conveyor-ui.zip)

**Comment by wrathagom** [comment]
@malave what is the syntax for using this?

**Comment by malave** [comment]
@wrathagom is the same as you originally mentioned:

```
{
...
  "hasDashboards": true,
  "hasAlerts": true,
  "hasLearning": false,
...
}
```
