### ISSUE TITLE
Flow Parameter name overwrites flow name

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#123]
Right now if a source uses the parameter `name` it overwrites the name of the channel that get's created. At least in the source definition the system one is `_name` maybe the form needs updated.

Or if we can't work around this, then we need to not allow a parameter `name`

**Comment by malave** [comment]
Parameter name validation is now working correctly the following will **not** be allowed:
- starting with `_`
- `name`
- `description`
- `index`

**Comment by malave** [comment]
@wrathagom I had to change the name of the parameter name in the `docker-sources` from `name` to `dockername` and this most likely will break something in the node-red flow

**Comment by wrathagom** [comment]
did you find replace all or just change the parameter name?

**Comment by malave** [comment]
I forgot to do it before pushing to master, I'm doing the replace and and testing (since the value is `name` it appears everywhere)
