### ISSUE TITLE
Release 1.3

### ISSUE THREAD

**Issue by milutz** [samtecspg/conveyor#131]
Template from gist https://gist.github.com/milutz/7712c37320ec062291abe435ac6bf0d5

- [x] Create a branch for the release, typiclly that should be in the format "X.Y" X=major, Y=minor - patch shouldn't be in the branch name (multiple patch releases might come off the same release branch)
```
git checkout master
git pull
git checkout -b 1.3
git push -u origin 1.3
```
- [x] Make sure ES software defaults are set to the desired ES release (for the `compose` install) - yes, set to 6.2.3
```
grep ELASTIC_TAG docker-compose.yml
grep ELASTIC_TAG build-compose-override.yml
grep 'ARG ELASTIC_TAG' plugin/Dockerfile
grep version plugin/package.json
```
- [x] Build the kibana plugin builder for that ES version
```
cd `mktemp -d` #optional
git clone https://github.com/samtecspg/kibana-plugin-build.git
cd kibana-plugin-build
./build-by-version.sh 6.2.3
```
- [x] Switch back to Conveyor, specifically the plugin directory and run the builder container there
```
cd ../conveyor/plugin
docker run --rm -it -v `pwd`:/kibana/plugin samtecspg/kibana-plugin-dev:6.2.3 bash
```
- [x] (in the build container) run the build and exit the container
```
cd plugin
yarn install
yarn build
# If you see an error  "pleaserun" *you forgot to `cd` into the plugin directory!*
exit
```
- [x] Update the project `docker-compose.yml` to pull the images for this release
```
cd ..
sed -i -- "s/repo-head/1.3.0/" docker-compose.yml
```
- [x] Do a test build and run to make sure it doesn't immediately blow for some reason
```
docker images
# Make sure there are any images matching the version your building in your cache!!
docker-compose -f docker-compose.yml -f build-compose-override.yml up
# do a CSV import, make sure basics work
```
- [x] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml plugin/build/conveyor-6.2.3.zip
git commit -m "Updates for 1.3.0 release"
git tag -a v1.3.0 -m "Release tag for 1.3.0 release"
git push
git push origin v1.3.0
```
- [x] (after docker cloud is done with the build) build the docker-compose zip file
```
./package.sh v1.3.0

```
- [ ] make a temp dir and test out the compose zip - do a `compose up` and test
```
mkdir tmpdir
unzip [where-ever-package-is.zip]
cd conveyoryX.X.X
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script
- [ ] In `master` update the readme to point to the new release
```
git checkout master
git pull
vi README.md
vi docs/_getting_started/basic-installation.md
git add README.md docs/_getting_started/basic-installation.md
git commit -m "Updating readme & docs to point and newest release"
```
- [ ] Update SPG Conveyer website to point at new release

**Comment by milutz** [comment]
Urg - they removed the canvas version we were using, and now the release requires ES 6.2.3 - fingers crossed that I can get this to work (this isn't supportable long term, though canvas should go final, then this problem my go away

**Comment by milutz** [comment]
Ok, have release shifted to ES 6.2.3 and pushed up my build (since docker hub doesn't seem to want to build right now)

Still needs a bit more double-checking and the remainder of the checklist

**Comment by milutz** [comment]
Trying again for a 1.3.1 release: (upload status bar fix)

Template from gist https://gist.github.com/milutz/7712c37320ec062291abe435ac6bf0d5

- [ ] Build the kibana plugin builder for that ES version
```
cd `mktemp -d` #optional
git clone https://github.com/samtecspg/kibana-plugin-build.git
cd kibana-plugin-build
./build-by-version.sh 6.2.3
```
- [ ] Switch back to Conveyor, specifically the plugin directory and run the builder container there
```
cd ../conveyor/plugin
docker run --rm -it -v `pwd`:/kibana/plugin samtecspg/kibana-plugin-dev:6.2.3 bash
```
- [ ] (in the build container) run the build and exit the container
```
cd plugin
yarn install
yarn build 
# If you see an error  "pleaserun" *you forgot to `cd` into the plugin directory!*
exit
```
- [ ] Update the project `docker-compose.yml` to pull the images for this release
```
cd ..
sed -i -- "s/repo-head/1.3.1/" docker-compose.yml
```
- [ ] Do a test build and run to make sure it doesn't immediately blow for some reason
```
docker images
# Make sure there are any images matching the version your building in your cache!!
docker-compose -f docker-compose.yml -f build-compose-override.yml up
# do a CSV import, make sure basics work
```
- [ ] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml plugin/build/conveyor-6.2.3.zip
git commit -m "Updates for 1.3.1 release"
git tag -a v1.3.1 -m "Release tag for 1.3.1 release"
git push
git push origin v1.3.1
```
- [ ] (after docker cloud is done with the build) build the docker-compose zip file
```
./package.sh v1.3.1

```
- [ ] make a temp dir and test out the compose zip - do a `compose up` and test
```
cd `mktemp -d`
pwd
unzip [where-ever-package-is.zip]
cd conveyoryX.X.X
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script
- [ ] In `master` update the readme to point to the new release
```
git checkout master
git pull
vi README.md
vi docs/_getting_started/basic-installation.md
git add README.md docs/_getting_started/basic-installation.md
git commit -m "Updating readme & docs to point and newest release"
```
- [ ] Update SPG Conveyer website to point at new release
- [ ] Update Conveyer docs to point at new release

**Comment by wrathagom** [comment]
@milutz so that's just the spg.ai/projects/conveyor site for me right? I got that one, think we're done.
