### ISSUE TITLE
compose error

### ISSUE THREAD

**Issue by shantanuo** [samtecspg/conveyor#150]
Could not install conveyor. Got this error:

> channel-load_1         | 2018/08/10 13:49:09 Problem with request: Get http://node-red:1880: dial tcp: lookup node-red on 127.0.0.11:53: no such host. Sleeping 10s
> channel-load_1         | 2018/08/10 13:49:09 Problem with request: Get http://kibana:5601: dial tcp: lookup kibana on 127.0.0.11:53: no such host. Sleeping 10s
> channel-load_1         | 2018/08/10 13:49:19 Problem with request: Get http://api:4000: dial tcp: lookup api on 127.0.0.11:53: no such host. Sleeping 10s
> channel-load_1         | 2018/08/10 13:49:19 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 10s
>

**Comment by malave** [comment]
Hi @shantanuo,

The `channel-load` service will keep pinging all services (every 10 seconds) until they are all up and it will show this message each time it pings a service and is not up yet. Having all services up could take a few minutes.

You should get an `Command finished successfully.` if everything went as expected.

Please let us know if you are not seen this message after 8 minutes (this is the timeout of the `channel-load` service)

**Comment by shantanuo** [comment]
The service is not up after waiting for more than 8 minutes.

**Comment by malave** [comment]
@shantanuo Can I get the entire log of `channel-load` from the start until it stops on its own?

**Comment by shantanuo** [comment]
Sure. 

https://todel162.s3.amazonaws.com/dba.txt

**Comment by wrathagom** [comment]
@shantanuo can you tell me what the output of `echo $UID` is?

**Comment by malave** [comment]
@shantanuo We saw that there are permission error within the kibana and elasticsearch containers:

```
[32mconveyorized-kibana_1  |[0m FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
```
and

```
[36melasticsearch_1        |[0m SettingsException[Failed to load settings from /usr/share/elasticsearch/config/elasticsearch.yml]; nested: AccessDeniedException[/usr/share/elasticsearch/config/elasticsearch.yml];
```

It could be related to mismatch UID ( some more info here:https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf )

**Comment by shantanuo** [comment]
Still the same problem. I bought a new EC2 instance and then installed docker, compose and conveyor. I got the same error on a new server as well.
```
# cat /etc/system-release
Amazon Linux 2
```
I did not try with ubuntu or any other distribution because as per our company policy, if something does not work on Amazon Linux, then we do not use it.

**Comment by wrathagom** [comment]
@shantanuo this is a Docker/ES issue more than it is related to Conveyor, though we definitely want to help you get it up and running. Did the logs on your EC2 instance have the same error messages in them?

```
[32mconveyorized-kibana_1  |�[0m FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
```
and
```
�[36melasticsearch_1        |�[0m SettingsException[Failed to load settings from /usr/share/elasticsearch/config/elasticsearch.yml]; nested: AccessDeniedException[/usr/share/elasticsearch/config/elasticsearch.yml];
```

What EC2 size did you choose, and did you do anything else before immeadietly installing Docker, Compose, and Conveyor? I will try to re-produce.

**Comment by wrathagom** [comment]
@shantanuo I just spun up a t2.large EC2 instance running Amazon Linux 2. This instance has 8G of RAM, which is little bit overkill, but 4G will likely not be enough. To run on a smaller VM, make sure you edit the RAM allocated to Elasticsearch in the compose file on this [line](https://github.com/samtecspg/conveyor/blob/master/docker-compose.yml#L22). 

For example to run on a t2.medium instance I would recommend:

```
     - ES_JAVA_OPTS=${ES_RAM:--Xmx2g -Xms2g}
```

Also, to get around the UID problem I had to `chown` the local storage folder recursively. But didn't have to add the user to the compose file.

```
sudo chown -R 1000:1000 local-storage/
```

**Comment by shantanuo** [comment]
@wrathagom Thanks for the tip. It worked. This is awesome by the way 👍

**Comment by wrathagom** [comment]
thanks, @shantanuo let us know if you have more troubles with it. Happy to help.
