### ISSUE TITLE
Installation on 6.4

### ISSUE THREAD

**Issue by spillz-dxb** [samtecspg/conveyor#158]
Received the following error during installation on kibana 6.4.1

Attempting to transfer from https://github.com/samtecspg/conveyor/releases/download/v1.4.0/conveyor-v1.4.0.zip
Transferring 3545 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by milutz** [comment]
@spillz-dxb Am I right in guessing that that transcript comes from `kibana-plugin install` ?

The release file that you list is our docker-based demo (IE it’s for standing up a complete ES instance that has conveyor preinstalled so you can try it out) - it’s **not** where the plugin binary is (it’s in the repo, but to use it a second element (the `conveyor-node`) needs to be installed as well, the complication of that is why we start by pointing people at the docker demo)

The steps for running the docker demo are at:  
https://github.com/samtecspg/conveyor/blob/master/README.md

I can talk you through doing a local install, but it’s slightly involved so we recommend trying the demo first.
