### ISSUE TITLE
Integrate Node-RED directly into Conveyor API as a library

### ISSUE THREAD

**Issue by milutz** [samtecspg/conveyor#43]
The current implementation of ingest requires that a standalone node-red be run in addition to ingest. The project would feel lighter-weight if node-red were directly integrated into ingest via the node-red library: https://nodered.org/docs/embedding

**Comment by wrathagom** [comment]
It is integrated - as a server - meaning we are still using the HTTP API to interact with it. per the Node-RED team the full node framework api is still not stable.
