### ISSUE TITLE
Better error messages and handling during channel creation

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#48]
## User Stories
 - As a channel creator I want to know why my flow failed to be created so that I can correct any mistakes I may have made.
 - As a channel creator I want flows that fail to be created in ES and Node-RED to be rolled back so that I am not left with dangling channels.

Right now there is a missing parameter I can see that in the console output, but the returned error just states `Invalid Flow Template Id or Parameter array supplied`. If we know that a parameter is missing we should return that to the user.

**Comment by malave** [comment]
@wrathagom, @ewoo: We should revisit this issue during the EUI update or shorty after. Most errors returned by the API are not shown or are not handled correctly in the UI. For example when there is an error on flow creation it just send you to the list page afterwards.

**Comment by wrathagom** [comment]
I'm fine with rolling it into the EUI changes. Given that you'll likely use something like the EUI toast to display the: https://elastic.github.io/eui/#/guidelines/toasts
