### ISSUE TITLE
Allow channel parameters to be grouped and toggled as a group

### ISSUE THREAD

**Issue by malave** [samtecspg/conveyor#50]
## User Stories:
 - As a Connector developer I want to be able to toggle parameters groups based on a selection criteria so that I can simplify the UI of more complex flows.
 - As a connector developer I want only the Parameters of visible groups to be validated/required.

### Original
We should be able to enable/disable sub-groups of parameters. This will also affect validations since this parameters even if they are required when enabled, will be optional when disabled

**Comment by wrathagom** [comment]
I think we've moved past this one.
