### ISSUE TITLE
Discover link in channel view

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#55]
## User Stories
 - [x] As a channel author/analyst I want to be able to quickly jump to the Discover page for a specific channel.

**Comment by wrathagom** [comment]
See this graphic, 3 dots on ride hand side of row for menu to delete (shown as edit) and discover.

![channels-screen 3x](https://user-images.githubusercontent.com/1779894/31254438-b262f692-a9f6-11e7-8689-20fd087c7a1c.png)

**Comment by malave** [comment]
@wrathagom What is going to appear in the Discover page?

**Comment by wrathagom** [comment]
Discover, is the top navigation item in Kibana, ideally it would be changed to the correct index alias which may require #38 before you can accomplish.

So for example for a source with an index of `bookings-demo` It would link to

```
http://localhost:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:bookings-demo,interval:auto,query:'')
```
