### ISSUE TITLE
Minify ZIP File

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#58]
The Kibana plugin helper is not minifying the build files as it operates in developer mode.

**Comment by malave** [comment]
When the zip is created using [kibana-plugin-helpers ](elastic/kibana-plugin-helpers) everything is placed in the zip file and is until kibana installs the plugin that this is `minified`, so with this I find out 2 things:

1.  The plugin is minified, but after installation

2.  Some other part of kibana is making the Chrome react plugin show that it is running on development.

So there is not much to do here at the moment.

**Comment by wrathagom** [comment]
interesting, learn something new each day.
