### ISSUE TITLE
Dynamic Form Description Helper Re-Design

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#59]
When the help text is too long it moves the subsequent group elements down the page instead of overflowing.

Luis mentioned redesigning this to be float above the grid as opposed to be a part of the grid.

**Comment by malave** [comment]
As mentioned in #60 we should move the box styling to surround just the inputs in a group but leave out the section for the description helper. The problem right now is that the we are using a grid to arrange and input and on the cel next to it we have the description helper, but there is no easy way to just style a column of that grid.

**Comment by wrathagom** [comment]
Closing as the whole UI is going to get re-implemented in EUI
