### ISSUE TITLE
Allow Help Text to contain basic HTML elements

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#70]
I know we discussed this one once and we were nervous about security implications, but I think we should revisit. Ideally we could use a library like https://www.npmjs.com/package/sanitize-html to limit what elements can be included in the help text.

**Comment by wrathagom** [comment]
I labeled this as just plugin, because really the API will accept it with rich text, it just doesn't get rendered.

**Comment by malave** [comment]
Ref commit: https://github.com/samtecspg/conveyor/commit/0380f6d7ac60ed7ce39bd15592330fc0da8ecb2d
