### ISSUE TITLE
would you mind to provide a docker image?

### ISSUE THREAD

**Issue by xycloud** [samtecspg/conveyor#85]

**Comment by wrathagom** [comment]
We have a compose in the root of the repo that spins up everything you need to test/trial Conveyor. Does that give you what you need?

We do want to provide a compose that uses pre-built images, but we have a few structural changes we need to make to the repo first.

**Comment by xycloud** [comment]
maybe provide a online demo is another good choice

**Comment by milutz** [comment]
@xycloud I'm still not quite tracking what your after

Are you after a quick demo of what Conveyor is?
Or a quick way to setup your instance? (If to setup your own instance, are you having issues with the `docker-compose` thats in the root of the project?)

We are certainly would like to help, but I don't follow what your after

**Comment by wrathagom** [comment]
Hey @xycloud not certain if you ever got what you need. Let us know if there's anything else we can help with. We'll have more docs/tuts/etc coming out soon.
